esphome:
  name: woonkamerrelais
  friendly_name: Woonkamerrelais

esp32:
  board: esp32dev
  framework:
    type: esp-idf

packages:
  core: !include poolcontrol_files/core.yaml

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "2bz1og0GzsCGfw2SyW+ec7pALpRMiWBQQsdbTvY0HA0="

ota:
  - platform: esphome
    password: "75bfcc31e0e2529c3a05c3b7465ec0d7"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Woonkamerrelais Fallback Hotspot"
    password: "QsQXw9GvukvC"

captive_portal:
    
web_server:
  port: 80
  version: 3
  js_url: https://oi.esphome.io/v3/www.js
   
# Example configuration entry for ESP32
i2c:
  sda: 4
  scl: 5
  scan: true
  id: bus_a

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

bluetooth_proxy:
  active: true
  connection_slots: 3

# Example configuration entry
#ethernet:
#  type: LAN8720
#  mdc_pin: GPIO23
# mdio_pin: GPIO18
# clk_mode: GPIO17_OUT
# phy_addr: 0

#  # Optional manual IP
#  manual_ip:
#    static_ip: 192.168.1.199
#    gateway: 192.168.1.1
#    subnet: 255.255.255.0 


# Example configuration entry
pcf8574:
  - id: 'pcf8574_hub_out_1'  # for output channel 1-8
    address: 0x24

  - id: 'pcf8574_hub_out_2'  # for output channel 9-16
    address: 0x25

  - id: 'pcf8574_hub_in_2'  # for input channel 1-8
    address: 0x21

  - id: 'pcf8574_hub_in_1'  # for input channel 9-16
    address: 0x22

# Individual outputs
switch:
  - platform: gpio
    name: "out1"
    pin:
      pcf8574: pcf8574_hub_out_1
      # Use pin number 0
      number: 0
      # One of INPUT or OUTPUT
      mode: OUTPUT
      inverted: false

  - platform: gpio
    name: "out2"
    pin:
      pcf8574: pcf8574_hub_out_1
      # Use pin number 1
      number: 1
      # One of INPUT or OUTPUT
      mode: OUTPUT
      inverted: true

  - platform: gpio
    name: "out3"
    pin:
      pcf8574: pcf8574_hub_out_1
      # Use pin number 2
      number: 2
      # One of INPUT or OUTPUT
      mode: OUTPUT
      inverted: true

  - platform: gpio
    name: "out4"
    pin:
      pcf8574: pcf8574_hub_out_1
      # Use pin number 3
      number: 3
      # One of INPUT or OUTPUT
      mode: OUTPUT
      inverted: true

  - platform: gpio
    name: "out5"
    pin:
      pcf8574: pcf8574_hub_out_1
      # Use pin number 4
      number: 4
      # One of INPUT or OUTPUT
      mode: OUTPUT
      inverted: true

  - platform: gpio
    name: "out6"
    pin:
      pcf8574: pcf8574_hub_out_1
      # Use pin number 5
      number: 5
      # One of INPUT or OUTPUT
      mode: OUTPUT
      inverted: true

  - platform: gpio
    name: "out7"
    pin:
      pcf8574: pcf8574_hub_out_1
      # Use pin number 6
      number: 6
      # One of INPUT or OUTPUT
      mode: OUTPUT
      inverted: true

  - platform: gpio
    name: "out8"
    pin:
      pcf8574: pcf8574_hub_out_1
      # Use pin number 7
      number: 7
      # One of INPUT or OUTPUT
      mode: OUTPUT
      inverted: true

  - platform: gpio
    name: "out9"
    pin:
      pcf8574: pcf8574_hub_out_2
      # Use pin number 0
      number: 0
      # One of INPUT or OUTPUT
      mode: OUTPUT
      inverted: true

  - platform: gpio
    name: "out10"
    pin:
      pcf8574: pcf8574_hub_out_2
      # Use pin number 1
      number: 1
      # One of INPUT or OUTPUT
      mode: OUTPUT
      inverted: true

  - platform: gpio
    name: "out11"
    pin:
      pcf8574: pcf8574_hub_out_2
      # Use pin number 2
      number: 2
      # One of INPUT or OUTPUT
      mode: OUTPUT
      inverted: true

  - platform: gpio
    name: "out12"
    pin:
      pcf8574: pcf8574_hub_out_2
      # Use pin number 3
      number: 3
      # One of INPUT or OUTPUT
      mode: OUTPUT
      inverted: true

  - platform: gpio
    name: "out13"
    pin:
      pcf8574: pcf8574_hub_out_2
      # Use pin number 4
      number: 4
      # One of INPUT or OUTPUT
      mode: OUTPUT
      inverted: true

  - platform: gpio
    name: "out14"
    pin:
      pcf8574: pcf8574_hub_out_2
      # Use pin number 5
      number: 5
      # One of INPUT or OUTPUT
      mode: OUTPUT
      inverted: true

  - platform: gpio
    name: "out15"
    pin:
      pcf8574: pcf8574_hub_out_2
      # Use pin number 6
      number: 6
      # One of INPUT or OUTPUT
      mode: OUTPUT
      inverted: true

  - platform: gpio
    name: "out16"
    pin:
      pcf8574: pcf8574_hub_out_2
      # Use pin number 7
      number: 7
      # One of INPUT or OUTPUT
      mode: OUTPUT
      inverted: true

binary_sensor:
  - platform: gpio
    name: "input1"
    pin:
      pcf8574: pcf8574_hub_in_1
      # Use pin number 0
      number: 0
      # One of INPUT or OUTPUT
      mode: INPUT
      inverted: true

  - platform: gpio
    name: "input2"
    pin:
      pcf8574: pcf8574_hub_in_1
      # Use pin number 1
      number: 1
      # One of INPUT or OUTPUT
      mode: INPUT
      inverted: true

  - platform: gpio
    name: "input3"
    pin:
      pcf8574: pcf8574_hub_in_1
      # Use pin number 2
      number: 2
      # One of INPUT or OUTPUT
      mode: INPUT
      inverted: true

  - platform: gpio
    name: "input4"
    pin:
      pcf8574: pcf8574_hub_in_1
      # Use pin number 3
      number: 3
      # One of INPUT or OUTPUT
      mode: INPUT
      inverted: true

  - platform: gpio
    name: "input5"
    pin:
      pcf8574: pcf8574_hub_in_1
      # Use pin number 4
      number: 4
      # One of INPUT or OUTPUT
      mode: INPUT
      inverted: true

  - platform: gpio
    name: "input6"
    pin:
      pcf8574: pcf8574_hub_in_1
      # Use pin number 5
      number: 5
      # One of INPUT or OUTPUT
      mode: INPUT
      inverted: true

  - platform: gpio
    name: "input7"
    pin:
      pcf8574: pcf8574_hub_in_1
      # Use pin number 6
      number: 6
      # One of INPUT or OUTPUT
      mode: INPUT
      inverted: true

  - platform: gpio
    name: "input8"
    pin:
      pcf8574: pcf8574_hub_in_1
      # Use pin number 7
      number: 7
      # One of INPUT or OUTPUT
      mode: INPUT
      inverted: true


  - platform: gpio
    name: "input9"
    pin:
      pcf8574: pcf8574_hub_in_2
      # Use pin number 0
      number: 0
      # One of INPUT or OUTPUT
      mode: INPUT
      inverted: true

  - platform: gpio
    name: "input10"
    pin:
      pcf8574: pcf8574_hub_in_2
      # Use pin number 1
      number: 1
      # One of INPUT or OUTPUT
      mode: INPUT
      inverted: true

  - platform: gpio
    name: "input11"
    pin:
      pcf8574: pcf8574_hub_in_2
      # Use pin number 2
      number: 2
      # One of INPUT or OUTPUT
      mode: INPUT
      inverted: true

  - platform: gpio
    name: "input12"
    pin:
      pcf8574: pcf8574_hub_in_2
      # Use pin number 3
      number: 3
      # One of INPUT or OUTPUT
      mode: INPUT
      inverted: true

  - platform: gpio
    name: "input13"
    pin:
      pcf8574: pcf8574_hub_in_2
      # Use pin number 4
      number: 4
      # One of INPUT or OUTPUT
      mode: INPUT
      inverted: true

  - platform: gpio
    name: "input14"
    pin:
      pcf8574: pcf8574_hub_in_2
      # Use pin number 5
      number: 5
      # One of INPUT or OUTPUT
      mode: INPUT
      inverted: true

  - platform: gpio
    name: "input15"
    pin:
      pcf8574: pcf8574_hub_in_2
      # Use pin number 6
      number: 6
      # One of INPUT or OUTPUT
      mode: INPUT
      inverted: true

  - platform: gpio
    name: "input16"
    pin:
      pcf8574: pcf8574_hub_in_2
      # Use pin number 7
      number: 7
      # One of INPUT or OUTPUT
      mode: INPUT
      inverted: true
