esphome:
  name: beacon
  friendly_name: beacon

esp32:
  board: esp32-poe
  framework:
    type: esp-idf
    

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "dxov3e1DMwvdFR1Y4b0urrWROkYPqayJT7FonPxOgbE="

ota:
  platform : esphome
  password: "00294e44b313732116ebd279e887c801"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Beacon Fallback Hotspot"
    password: "BRovBi9pOeVt"

captive_portal:

# Example configuration entry
esp32_ble_beacon:
  type: iBeacon
  uuid: 'c29ce823-e67a-4e71-bff2-abaa32e77a98'