esphome:
  name: boe
  friendly_name: boe

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "V7EPzb6aPzcvGaTaAT2yR8i7mHsdoCOB8U4rHrHzC+M="

ota:
  - platform: esphome
    password: "207cc3bbeb6075ff4225d458b44ee9b7"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Boe Fallback Hotspot"
    password: "CHUBnHJIUhq8"

captive_portal:
    