esphome:
  name: relay
  friendly_name: relay

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "/609StMXMrdj+JViL9LpMES0kOGD+R6+GUEFDy7kS44="

ota:
  platform: esphome
  password: "f3a764e01a46a8bef9abf6d4b21b8d22"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Relay Fallback Hotspot"
    password: "2yu7P3AeoeC1"

captive_portal:

web_server:

switch:
- platform: gpio
  pin: 0
  name: "Pool roof valve" 
  restore_mode: RESTORE_DEFAULT_ON