esphome:
  friendly_name: rgbdouche
  name: ${esphome_name}
  platformio_options:
    board_build.flash_mode: dio

# Enable Home Assistant API
api:
  reboot_timeout: 60min
  encryption:
    key: "zSnmlbekW7UFZdlzonu7Vo9bQFH6ppnX9nDsCszNzPI="
#  password: !secret esphome_api_pass

ota:
  - platform: esphome
    password: "8597b8d1000f59777fa653f2526320d4"
#    password: !secret esphome_ota_pass

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Rgbdouche Fallback Hotspot"
    password: "EcmXg3ALWEL6"

captive_portal:


substitutions:
  esphome_name: rgbdouche

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf


#Disable logging/UART
logger:
# level: NONE
  baud_rate: 0



time:
  - platform: homeassistant
    id: homeassistant_time

web_server:
  port: 80

i2c:
  sda: GPIO6
  scl: GPIO7
  scan: true
  id: I2C

sensor:
  - platform: uptime
    name: "${esphome_name} Uptime Sensor"
    
  - platform: wifi_signal
    name: "${esphome_name} WiFi Signal"
    update_interval: 60s

  - platform: internal_temperature
    name: "${esphome_name} Internal Temperature"
    accuracy_decimals: 2
    update_interval: 30s

switch:
  - platform: restart
    name: ${esphome_name}-restart
    id: restart_switch
    
binary_sensor:
  - platform: gpio
    pin: 2
    name: ${esphome_name}-Button_1
    filters:
      - invert:

  - platform: gpio
    pin: 8
    name: ${esphome_name}-Button_2
    filters:
      - invert:

  - platform: gpio
    pin: 9
    name: ${esphome_name}-Button_3
    filters:
      - invert:

output:
  - platform: ledc
    pin: GPIO5
    frequency: 19531Hz
    id: LED_channel_1

  - platform: ledc
    pin: GPIO4
    frequency: 19531Hz
    id: LED_channel_2

  - platform: ledc
    pin: GPIO1
    frequency: 19531Hz
    id: LED_channel_3

  - platform: ledc
    pin: GPIO0
    frequency: 19531Hz
    id: LED_channel_4

  - platform: ledc
    pin: GPIO3
    frequency: 19531Hz
    id: LED_channel_5


light:
  - platform: rgbww
    name: "Douche licht"
    red: LED_channel_5
    green: LED_channel_4
    blue: LED_channel_3
    cold_white: LED_channel_2
    warm_white: LED_channel_1
    cold_white_color_temperature: 6536 K
    warm_white_color_temperature: 2000 K