esphome:
  name: ups-power-ok
  friendly_name: UPS-power-ok
  on_boot:
    priority: -100  # Wait until other things have initialized
    then:
    - logger.log: "Boot complete"

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "Mu0xANZXM9Mm1X79P9O5Qc3oRA/NubIrMrksXRgD1Vk="

ota:
  - platform: esphome
    password: "8ea7acae1809394121710049c0080cf2"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

 # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Ups-Power-Ok Fallback Hotspot"
    password: "ZOx0w0A1LGkP"

captive_portal:

web_server:

#ethernet:
#  type: LAN8720
#  mdc_pin: GPIO23
#  mdio_pin: GPIO18
#  clk_mode: GPIO17_OUT
#  phy_addr: 0
#  power_pin: GPIO12


# Example configuration entry
text_sensor:
  - platform: wifi_info
    ip_address:
      name: ESP IP Address
    dns_address:
      name: ESP DNS Address
    mac_address:
      name: ESP MAC Address

binary_sensor:
  - platform: gpio
    name: "BAT low"
    pin:
      number: GPIO13
      mode:
        input: true
        pullup: true
      inverted: true

  - platform: gpio
    name: "Power failure"
    pin:
      number: GPIO14
      mode:
        input: true
        pullup: true
      inverted: true

button:
  - platform: template
    name: "Shutdown HA"
    on_press:
     then:
        - logger.log: "Power failure detected! Shutting down Home Assistant."
      
      
switch:
  - platform: gpio
    name: "Reboot Raspberry Pi"
    pin: GPIO15
    id: pi_reboot
    inverted: false
    restore_mode: always_off

